title: Osaetin daniel
email: osaetindaniel@gmail.com
description: An Open source blog where i keep my findings in the ever exciting world of programming
url: "https://danidee10.github.io"
twitter_username: osaetindaniel
github_username:  danidee10

# Where things are
source:      .
destination: ./_site
plugins_dir:     ./_plugins
layouts_dir:     ./_layouts
data_dir: ./_data
collections: null

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
paginate: 5
paginate_path: "/blog/page:num/"

# Filtering Content
show_drafts: null
limit_posts: 0
future:      true
unpublished: false

# Plugins
whitelist: []
#gems:      ['jekyll-github-metadata']

# Conversion
markdown:    kramdown
highlighter: rouge
linenos:     false
lsi:         false
excerpt_separator: "\n\n"

# Serving
detach:  false
port:    4000
host:    127.0.0.1
baseurl: "" # does not include hostname

# Outputting
permalink:     date
timezone:      null

quiet:    false
defaults: []

# Markdown Processors
rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  syntax_highlighter: rouge
  line_numbers: false

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style
